# Generated by Django 4.2.16 on 2024-12-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Stack", "0002_alter_portfolio_user_alter_transaction_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=500000.0, max_digits=10
            ),
        ),
        migrations.DeleteModel(
            name="Balance",
        ),
    ]
