# Generated by Django 4.2.16 on 2024-12-06 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Stack", "0003_profile_balance_delete_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stack_user_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
