# Generated by Django 4.2.16 on 2024-12-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Stack", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
