# Generated by Django 4.2.16 on 2024-12-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Stack", "0005_alter_profile_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
