# Generated by Django 4.2.16 on 2024-12-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Stack", "0006_rename_timestamp_transaction_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="https://cdn.creazilla.com/cliparts/3153276/user-clipart-xl.png",
                null=True,
            ),
        ),
    ]
